var assert = require('assert');
var weeklySales = require('../functions/weeklySales');
var mostPopularProduct = require('../functions/mostPopularProduct');
var leastPopularProduct = require('../functions/leastPopularProduct');
var mostPopularCategory = require('../functions/mostPopularCategory');
var leastPopularCatergory = require('../functions/leastPopularCategory');
var mostProfitableProduct = require('../functions/mostProfitableProduct');
var mostProfitableCategory = require("../functions/mostProfitableCategory");
var purchases = require("../functions/purchases");
var sales = require('../functions/Sales');

 describe("weeklySales", function(){
  it("should return a list of weekly products sold, quantity of each product sold and single price per item .", function(){
    var result = weeklySales.weeklySales(1);
    assert.deepEqual(result,
      [ { stockItem: 'Apples - loose', sold: 36, singlePrice: 2 }, //WEEK 1
    { stockItem: 'Bananas - loose', sold: 47, singlePrice: 2 },
    { stockItem: 'Bread', sold: 45, singlePrice: 12 },
    { stockItem: 'Chakalaka Can', sold: 23, singlePrice: 10 },
    { stockItem: 'Coke 500ml', sold: 54, singlePrice: 6.5 },
    { stockItem: 'Cream Soda 500ml', sold: 22, singlePrice: 7.5 },
    { stockItem: 'Fanta 500ml', sold: 33, singlePrice: 6.5 },
    { stockItem: 'Gold Dish Vegetable Curry Can',
      sold: 17,
      singlePrice: 9 },
    { stockItem: 'Imasi', sold: 30, singlePrice: 25 },
    { stockItem: 'Iwisa Pap 5kg', sold: 17, singlePrice: 30 },
    { stockItem: 'Milk 1l', sold: 39, singlePrice: 10 },
    { stockItem: 'Mixed Sweets 5s', sold: 49, singlePrice: 3 },
    { stockItem: 'Shampoo 1 litre', sold: 3, singlePrice: 30 },
    { stockItem: 'Soap Bar', sold: 12, singlePrice: 6 },
    { stockItem: 'Top Class Soy Mince', sold: 22, singlePrice: 12 } ],

    [ { stockItem: 'Apples - loose', sold: 0, singlePrice: 2 }, //Week2
      { stockItem: 'Bananas - loose', sold: 14, singlePrice: 2 },
      { stockItem: 'Bread', sold: 14, singlePrice: 12 },
      { stockItem: 'Chakalaka Can', sold: 0, singlePrice: 10 },
      { stockItem: 'Coke 500ml', sold: 98, singlePrice: 6.5 },
      { stockItem: 'Cream Soda 500ml', sold: 7, singlePrice: 7.5 },
      { stockItem: 'Fanta 500ml', sold: 0, singlePrice: 6.5 },
      { stockItem: 'Gold Dish Vegetable Curry Can',
        sold: 0,
        singlePrice: 9 },
      { stockItem: 'Heart Chocolates', sold: 0, singlePrice: 35 },
      { stockItem: 'Imasi', sold: 28, singlePrice: 25 },
      { stockItem: 'Iwisa Pap 5kg', sold: 7, singlePrice: 30 },
      { stockItem: 'Milk 1l', sold: 21, singlePrice: 10 },
      { stockItem: 'Mixed Sweets 5s', sold: 21, singlePrice: 3 },
      { stockItem: 'Shampoo 1 litre', sold: 0, singlePrice: 30 },
      { stockItem: 'Soap Bar', sold: 0, singlePrice: 6 },
      { stockItem: 'Top Class Soy Mince', sold: 14, singlePrice: 12 },
      { stockItem: 'Valentine Cards', sold: 42, singlePrice: 4 } ],

      [ { stockItem: 'Apples - loose', sold: 25, singlePrice: 2 }, //WEEK 3
      { stockItem: 'Bananas - loose', sold: 17, singlePrice: 2 },
      { stockItem: 'Bread', sold: 24, singlePrice: 12 },
      { stockItem: 'Chakalaka Can', sold: 17, singlePrice: 10 },
      { stockItem: 'Coke 500ml', sold: 18, singlePrice: 6.5 },
      { stockItem: 'Cream Soda 500ml', sold: 12, singlePrice: 7.5 },
      { stockItem: 'Fanta 500ml', sold: 14, singlePrice: 6.5 },
      { stockItem: 'Gold Dish Vegetable Curry Can',sold: 8,singlePrice: 9 },
      { stockItem: 'Imasi', sold: 25, singlePrice: 25 },
      { stockItem: 'Iwisa Pap 5kg', sold: 4, singlePrice: 30 },
      { stockItem: 'Milk 1l', sold: 30, singlePrice: 10 },
      { stockItem: 'Mixed Sweets 5s', sold: 29, singlePrice: 2 },
      { stockItem: 'Shampoo 1 litre', sold: 4, singlePrice: 30 },
      { stockItem: 'Soap Bar', sold: 8, singlePrice: 6 },
      { stockItem: 'Top Class Soy Mince', sold: 12, singlePrice: 12 } ],

      [ { stockItem: 'Apples - loose', sold: 7, singlePrice: 2 },
         { stockItem: 'Apples - loose', sold: 56, singlePrice: 2 },
         { stockItem: 'Bananas - loose', sold: 35, singlePrice: 2 },
         { stockItem: 'Bread', sold: 35, singlePrice: 12 },
         { stockItem: 'Chakalaka Can', sold: 21, singlePrice: 10 },
         { stockItem: 'Coke 500ml', sold: 21, singlePrice: 6.5 },
         { stockItem: 'Cream Soda 500ml', sold: 0, singlePrice: 7.5 },
         { stockItem: 'Fanta 500ml', sold: 7, singlePrice: 6.5 },
         { stockItem: 'Gold Dish Vegetable Curry Can',
           sold: 7,
           singlePrice: 9 },
         { stockItem: 'Gold Dish Vegetable Curry Can',
           sold: 63,
           singlePrice: 9 },
         { stockItem: 'Imasi', sold: 42, singlePrice: 25 },
         { stockItem: 'Iwisa Pap 5kg', sold: 21, singlePrice: 30 },
         { stockItem: 'Milk 1l', sold: 56, singlePrice: 10 },
         { stockItem: 'Mixed Sweets 5s', sold: 21, singlePrice: 3 },
         { stockItem: 'Shampoo 1 litre', sold: 0, singlePrice: 30 },
         { stockItem: 'Soap Bar', sold: 7, singlePrice: 6 },
         { stockItem: 'Top Class Soy Mince', sold: 0, singlePrice: 12 },
         { stockItem: 'Top Class Soy Mince', sold: 63, singlePrice: 12 } ]
);
  });

});

describe("mostPopularProduct",function(){
  it("should return the most popular product sold each week", function(){
    var result = mostPopularProduct.mostPopularProduct(1);
    assert.deepEqual(result, ['Coke 500ml'], ["Coke 500ml"], ["Milk 1l"], ['Gold Dish Vegetable Curry Can']);
  });
});

describe("leastPopularProduct",function(){
  it("should return the least popular product of each week",function(){
    var result = leastPopularProduct.leastPopularProducts(1);
    assert.deepEqual(result,
      ["Shampoo 1 litre"],
    ["Heart Chocolates"],
    ["Shampoo 1 litre"],
    ["Top Class Soy Mince"]
  );
  });
});

describe("popularCatergoryWeek1",function(){
  it("should return the most popular catergory for week 1", function(){
    var result=mostPopularCategory.popularCatergory(1);
    assert.equal(result, "Sweets", "Sweets", "Dairy", "Canned_Goods");
  });
});

//
describe("mostProfitableProduct",function(){
  it("should return the most profitable product of each week",function(){
    var result = mostProfitableProduct.mostProfitableProduct(1);
    assert.deepEqual(result,"Imasi","Imasi","Imasi","Imasi");
  });
});

describe("leastPopularCategory", function(){
  it("should return the least popular category for each week", function(){
    var result=leastPopularCatergory.leastPopularCatergory(1);
    assert.equal(result, "Hygiene","Canned_Goods", "Hygiene", "Meat");
  });
});
//
describe("mostProfitableCategory",function(){
  it("should return the most profitable category of each week",function(){
    var result = mostProfitableCategory.mostProfitableCategory(1);
    assert.deepEqual(result,"Dairy", "Dairy", "Dairy", "Dairy");
  });
});

describe("purchases",function(){
  it("should return the most profitable category of each week",function(){
    var result =purchases.purchases();
    assert.deepEqual(result,
      [ { date: '23-Jan',
    item: 'Chakalaka Can',
    quantity: '3',
    cost: '7,00',
    total: '21,00' },
  { date: '23-Jan',
    item: 'Coke 500ml',
    quantity: '3',
    cost: '3,50',
    total: '10,50' },
  { date: '23-Jan',
    item: 'Cream Soda 500ml',
    quantity: '4',
    cost: '4,50',
    total: '18,00' },
  { date: '23-Jan',
    item: 'Fanta 500ml',
    quantity: '2',
    cost: '4,50',
    total: '9,00' },
  { date: '23-Jan',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '2',
    cost: '5,00',
    total: '10,00' },
  { date: '23-Jan',
    item: 'Imasi',
    quantity: '1',
    cost: '17,00',
    total: '17,00' },
  { date: '23-Jan',
    item: 'Iwisa Pap 5kg',
    quantity: '3',
    cost: '20,00',
    total: '60,00' },
  { date: '23-Jan',
    item: 'Milk 1l',
    quantity: '4',
    cost: '7,00',
    total: '28,00' },
  { date: '23-Jan',
    item: 'Top Class Soy Mince',
    quantity: '5',
    cost: '8,00',
    total: '40,00' },
  { date: '28-Jan',
    item: 'Bananas - loose',
    quantity: '4',
    cost: '1,00',
    total: '4,00' },
  { date: '28-Jan',
    item: 'Apples - loose',
    quantity: '10',
    cost: '1,50',
    total: '15,00' },
  { date: '28-Jan',
    item: 'Mixed Sweets 5s',
    quantity: '60',
    cost: '3,00',
    total: '180,00' },
  { date: '28-Jan',
    item: 'Shampoo 1 litre',
    quantity: '1',
    cost: '20,00',
    total: '20,00' },
  { date: '28-Jan',
    item: 'Soap Bar',
    quantity: '3',
    cost: '3,00',
    total: '9,00' },
  { date: '28-Jan',
    item: 'Bread',
    quantity: '30',
    cost: '9,00',
    total: '270,00' },
  { date: '28-Jan',
    item: 'Chakalaka Can',
    quantity: '15',
    cost: '7,00',
    total: '105,00' },
  { date: '28-Jan',
    item: 'Coke 500ml',
    quantity: '36',
    cost: '3,50',
    total: '126,00' },
  { date: '28-Jan',
    item: 'Cream Soda 500ml',
    quantity: '24',
    cost: '4,50',
    total: '108,00' },
  { date: '28-Jan',
    item: 'Fanta 500ml',
    quantity: '24',
    cost: '4,50',
    total: '108,00' },
  { date: '28-Jan',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '15',
    cost: '5,00',
    total: '75,00' },
  { date: '28-Jan',
    item: 'Imasi',
    quantity: '15',
    cost: '17,00',
    total: '255,00' },
  { date: '28-Jan',
    item: 'Iwisa Pap 5kg',
    quantity: '15',
    cost: '20,00',
    total: '300,00' },
  { date: '28-Jan',
    item: 'Milk 1l',
    quantity: '25',
    cost: '7,00',
    total: '175,00' },
  { date: '28-Jan',
    item: 'Top Class Soy Mince',
    quantity: '10',
    cost: '8,00',
    total: '80,00' },
  { date: '02-Feb',
    item: 'Shampoo 1 litre',
    quantity: '1',
    cost: '20,00',
    total: '20,00' },
  { date: '02-Feb',
    item: 'Soap Bar',
    quantity: '3',
    cost: '3,00',
    total: '9,00' },
  { date: '03-Feb',
    item: 'Bananas - loose',
    quantity: '12',
    cost: '1,00',
    total: '12,00' },
  { date: '03-Feb',
    item: 'Apples - loose',
    quantity: '100',
    cost: '1,50',
    total: '150,00' },
  { date: '03-Feb',
    item: 'Mixed Sweets 5s',
    quantity: '240',
    cost: '3,00',
    total: '720,00' },
  { date: '04-Feb',
    item: 'Shampoo 1 litre',
    quantity: '2',
    cost: '20,00',
    total: '40,00' },
  { date: '04-Feb',
    item: 'Soap Bar',
    quantity: '5',
    cost: '3,00',
    total: '15,00' },
  { date: '04-Feb',
    item: 'Bread',
    quantity: '4',
    cost: '11,00',
    total: '44,00' },
  { date: '04-Feb',
    item: 'Imasi',
    quantity: '4',
    cost: '24,00',
    total: '96,00' },
  { date: '06-Feb',
    item: 'Bananas - loose',
    quantity: '8',
    cost: '1,00',
    total: '8,00' },
  { date: '06-Feb',
    item: 'Apples - loose',
    quantity: '100',
    cost: '1,50',
    total: '150,00' },
  { date: '06-Feb',
    item: 'Mixed Sweets 5s',
    quantity: '150',
    cost: '3,00',
    total: '450,00' },
  { date: '06-Feb',
    item: 'Soap Bar',
    quantity: '5',
    cost: '3,00',
    total: '15,00' },
  { date: '6-Feb',
    item: 'Bread',
    quantity: '30',
    cost: '9,00',
    total: '270,00' },
  { date: '6-Feb',
    item: 'Chakalaka Can',
    quantity: '15',
    cost: '7,00',
    total: '105,00' },
  { date: '6-Feb',
    item: 'Coke 500ml',
    quantity: '36',
    cost: '3,50',
    total: '126,00' },
  { date: '6-Feb',
    item: 'Cream Soda 500ml',
    quantity: '18',
    cost: '4,50',
    total: '81,00' },
  { date: '6-Feb',
    item: 'Fanta 500ml',
    quantity: '24',
    cost: '4,50',
    total: '108,00' },
  { date: '6-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '15',
    cost: '5,00',
    total: '75,00' },
  { date: '6-Feb',
    item: 'Imasi',
    quantity: '25',
    cost: '17,00',
    total: '425,00' },
  { date: '6-Feb',
    item: 'Iwisa Pap 5kg',
    quantity: '5',
    cost: '20,00',
    total: '100,00' },
  { date: '6-Feb',
    item: 'Milk 1l',
    quantity: '10',
    cost: '7,00',
    total: '70,00' },
  { date: '6-Feb',
    item: 'Top Class Soy Mince',
    quantity: '10',
    cost: '8,00',
    total: '80,00' },
  { date: '09-Feb',
    item: 'ose (plastic)',
    quantity: '20',
    cost: '10,00',
    total: '200,00' },
  { date: '09-Feb',
    item: 'Milk 1l',
    quantity: '3',
    cost: '9,50',
    total: '28,50' },
  { date: '10-Feb',
    item: 'Bananas - loose',
    quantity: '4',
    cost: '1,00',
    total: '4,00' },
  { date: '10-Feb',
    item: 'Apples - loose',
    quantity: '20',
    cost: '1,50',
    total: '30,00' },
  { date: '10-Feb',
    item: 'Mixed Sweets 5s',
    quantity: '150',
    cost: '3,00',
    total: '450,00' },
  { date: '10-Feb',
    item: 'Bread',
    quantity: '10',
    cost: '9,00',
    total: '90,00' },
  { date: '10-Feb',
    item: 'Chakalaka Can',
    quantity: '15',
    cost: '7,00',
    total: '105,00' },
  { date: '10-Feb',
    item: 'Coke 500ml',
    quantity: '18',
    cost: '3,50',
    total: '63,00' },
  { date: '10-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '5',
    cost: '5,00',
    total: '25,00' },
  { date: '10-Feb',
    item: 'Heart Chocolates',
    quantity: '20',
    cost: '25,00',
    total: '500,00' },
  { date: '10-Feb',
    item: 'Imasi',
    quantity: '10',
    cost: '17,00',
    total: '170,00' },
  { date: '10-Feb',
    item: 'Iwisa Pap 5kg',
    quantity: '5',
    cost: '20,00',
    total: '100,00' },
  { date: '10-Feb',
    item: 'Milk 1l',
    quantity: '10',
    cost: '7,00',
    total: '70,00' },
  { date: '10-Feb',
    item: 'Top Class Soy Mince',
    quantity: '15',
    cost: '8,00',
    total: '120,00' },
  { date: '11-Feb',
    item: 'Shampoo 1 litre',
    quantity: '2',
    cost: '20,00',
    total: '40,00' },
  { date: '11-Feb',
    item: 'Valentine Cards',
    quantity: '20',
    cost: '2,00',
    total: '40,00' },
  { date: '12-Feb',
    item: 'Milk 1l',
    quantity: '3',
    cost: '9,50',
    total: '28,50' },
  { date: '13-Feb',
    item: 'Bananas - loose',
    quantity: '4',
    cost: '1,00',
    total: '4,00' },
  { date: '13-Feb',
    item: 'Mixed Sweets 5s',
    quantity: '50',
    cost: '3,00',
    total: '150,00' },
  { date: '13-Feb',
    item: 'Shampoo 1 litre',
    quantity: '3',
    cost: '20,00',
    total: '60,00' },
  { date: '13-Feb',
    item: 'Soap Bar',
    quantity: '5',
    cost: '3,00',
    total: '15,00' },
  { date: '13-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '5',
    cost: '8,50',
    total: '42,50' },
  { date: '13-Feb',
    item: 'Bread',
    quantity: '5',
    cost: '9,00',
    total: '45,00' },
  { date: '13-Feb',
    item: 'Coke 500ml',
    quantity: '12',
    cost: '3,50',
    total: '42,00' },
  { date: '13-Feb',
    item: 'Fanta 500ml',
    quantity: '12',
    cost: '4,50',
    total: '54,00' },
  { date: '13-Feb',
    item: 'Imasi',
    quantity: '20',
    cost: '17,00',
    total: '340,00' },
  { date: '13-Feb',
    item: 'Milk 1l',
    quantity: '15',
    cost: '7,00',
    total: '105,00' },
  { date: '13-Feb',
    item: 'Top Class Soy Mince',
    quantity: '5',
    cost: '8,00',
    total: '40,00' },
  { date: '14-Feb',
    item: 'Shampoo 1 litre',
    quantity: '1',
    cost: '20,00',
    total: '20,00' },
  { date: '14-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '2',
    cost: '8,50',
    total: '17,00' },
  { date: '16-Feb',
    item: 'Chakalaka Can',
    quantity: '2',
    cost: '8,50',
    total: '17,00' },
  { date: '16-Feb',
    item: 'Cream Soda 500ml',
    quantity: '2',
    cost: '7,50',
    total: '15,00' },
  { date: '16-Feb',
    item: 'Fanta 500ml',
    quantity: '1',
    cost: '6,50',
    total: '6,50' },
  { date: '16-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '2',
    cost: '8,50',
    total: '17,00' },
  { date: '16-Feb',
    item: 'Iwisa Pap 5kg',
    quantity: '1',
    cost: '30,00',
    total: '30,00' },
  { date: '16-Feb',
    item: 'Milk 1l',
    quantity: '6',
    cost: '9,50',
    total: '57,00' },
  { date: '17-Feb',
    item: 'Apples - loose',
    quantity: '60',
    cost: '1,50',
    total: '90,00' },
  { date: '17-Feb',
    item: 'Mixed Sweets 5s',
    quantity: '12',
    cost: '3,00',
    total: '36,00' },
  { date: '17-Feb',
    item: 'Bread',
    quantity: '15',
    cost: '9,00',
    total: '135,00' },
  { date: '17-Feb',
    item: 'Chakalaka Can',
    quantity: '10',
    cost: '7,00',
    total: '70,00' },
  { date: '17-Feb',
    item: 'Coke 500ml',
    quantity: '24',
    cost: '3,50',
    total: '84,00' },
  { date: '17-Feb',
    item: 'Cream Soda 500ml',
    quantity: '12',
    cost: '4,50',
    total: '54,00' },
  { date: '17-Feb',
    item: 'Fanta 500ml',
    quantity: '12',
    cost: '4,50',
    total: '54,00' },
  { date: '17-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '10',
    cost: '5,00',
    total: '50,00' },
  { date: '17-Feb',
    item: 'Imasi',
    quantity: '15',
    cost: '17,00',
    total: '255,00' },
  { date: '17-Feb',
    item: 'Iwisa Pap 5kg',
    quantity: '5',
    cost: '20,00',
    total: '100,00' },
  { date: '17-Feb',
    item: 'Milk 1l',
    quantity: '15',
    cost: '7,00',
    total: '105,00' },
  { date: '17-Feb',
    item: 'Top Class Soy Mince',
    quantity: '5',
    cost: '8,00',
    total: '40,00' },
  { date: '18-Feb',
    item: 'Shampoo 1 litre',
    quantity: '1',
    cost: '20,00',
    total: '20,00' },
  { date: '18-Feb',
    item: 'Soap Bar',
    quantity: '5',
    cost: '3,00',
    total: '15,00' },
  { date: '19-Feb',
    item: 'Shampoo 1 litre',
    quantity: '2',
    cost: '20,00',
    total: '40,00' },
  { date: '19-Feb',
    item: 'Milk 1l',
    quantity: '1',
    cost: '9,50',
    total: '9,50' },
  { date: '20-Feb',
    item: 'Bananas - loose',
    quantity: '20',
    cost: '1,00',
    total: '20,00' },
  { date: '20-Feb',
    item: 'Apples - loose',
    quantity: '90',
    cost: '1,50',
    total: '135,00' },
  { date: '20-Feb',
    item: 'Mixed Sweets 5s',
    quantity: '20',
    cost: '3,00',
    total: '60,00' },
  { date: '20-Feb',
    item: 'Shampoo 1 litre',
    quantity: '2',
    cost: '20,00',
    total: '40,00' },
  { date: '20-Feb',
    item: 'Soap Bar',
    quantity: '3',
    cost: '3,00',
    total: '9,00' },
  { date: '20-Feb',
    item: 'Bread',
    quantity: '10',
    cost: '9,00',
    total: '90,00' },
  { date: '20-Feb',
    item: 'Imasi',
    quantity: '10',
    cost: '17,00',
    total: '170,00' },
  { date: '20-Feb',
    item: 'Iwisa Pap 5kg',
    quantity: '5',
    cost: '20,00',
    total: '100,00' },
  { date: '20-Feb',
    item: 'Milk 1l',
    quantity: '15',
    cost: '7,00',
    total: '105,00' },
  { date: '20-Feb',
    item: 'Top Class Soy Mince',
    quantity: '10',
    cost: '8,00',
    total: '80,00' },
  { date: '23-Feb',
    item: 'Chakalaka Can',
    quantity: '3',
    cost: '9,00',
    total: '27,00' },
  { date: '24-Feb',
    item: 'Bananas - loose',
    quantity: '10',
    cost: '1,00',
    total: '10,00' },
  { date: '24-Feb',
    item: 'Apples - loose',
    quantity: '90',
    cost: '1,50',
    total: '135,00' },
  { date: '24-Feb',
    item: 'Mixed Sweets 5s',
    quantity: '8',
    cost: '3,00',
    total: '24,00' },
  { date: '24-Feb',
    item: 'Bread',
    quantity: '15',
    cost: '9,00',
    total: '135,00' },
  { date: '24-Feb',
    item: 'Chakalaka Can',
    quantity: '10',
    cost: '7,00',
    total: '70,00' },
  { date: '24-Feb',
    item: 'Coke 500ml',
    quantity: '18',
    cost: '3,50',
    total: '63,00' },
  { date: '24-Feb',
    item: 'Cream Soda 500ml',
    quantity: '6',
    cost: '4,50',
    total: '27,00' },
  { date: '24-Feb',
    item: 'Fanta 500ml',
    quantity: '6',
    cost: '4,50',
    total: '27,00' },
  { date: '24-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '10',
    cost: '5,00',
    total: '50,00' },
  { date: '24-Feb',
    item: 'Imasi',
    quantity: '15',
    cost: '17,00',
    total: '255,00' },
  { date: '24-Feb',
    item: 'Milk 1l',
    quantity: '20',
    cost: '7,00',
    total: '140,00' },
  { date: '24-Feb',
    item: 'Top Class Soy Mince',
    quantity: '15',
    cost: '8,00',
    total: '120,00' },
  { date: '25-Feb',
    item: 'Soap Bar',
    quantity: '5',
    cost: '3,00',
    total: '15,00' },
  { date: '26-Feb',
    item: 'Shampoo 1 litre',
    quantity: '2',
    cost: '20,00',
    total: '40,00' },
  { date: '26-Feb',
    item: 'Soap Bar',
    quantity: '5',
    cost: '3,00',
    total: '15,00' },
  { date: '26-Feb',
    item: 'Bread',
    quantity: '1',
    cost: '11,00',
    total: '11,00' },
  { date: '26-Feb',
    item: 'Fanta 500ml',
    quantity: '2',
    cost: '6,50',
    total: '13,00' },
  { date: '26-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '1',
    cost: '8,50',
    total: '8,50' },
  { date: '26-Feb',
    item: 'Iwisa Pap 5kg',
    quantity: '1',
    cost: '30,00',
    total: '30,00' },
  { date: '27-Feb',
    item: 'Bananas - loose',
    quantity: '10',
    cost: '1,00',
    total: '10,00' },
  { date: '27-Feb',
    item: 'Apples - loose',
    quantity: '60',
    cost: '1,50',
    total: '90,00' },
  { date: '27-Feb',
    item: 'Shampoo 1 litre',
    quantity: '5',
    cost: '20,00',
    total: '100,00' },
  { date: '27-Feb',
    item: 'Soap Bar',
    quantity: '5',
    cost: '3,00',
    total: '15,00' },
  { date: '27-Feb',
    item: 'Bread',
    quantity: '20',
    cost: '9,00',
    total: '180,00' },
  { date: '27-Feb',
    item: 'Chakalaka Can',
    quantity: '15',
    cost: '7,00',
    total: '105,00' },
  { date: '27-Feb',
    item: 'Coke 500ml',
    quantity: '24',
    cost: '3,50',
    total: '84,00' },
  { date: '27-Feb',
    item: 'Cream Soda 500ml',
    quantity: '12',
    cost: '4,50',
    total: '54,00' },
  { date: '27-Feb',
    item: 'Fanta 500ml',
    quantity: '12',
    cost: '4,50',
    total: '54,00' },
  { date: '27-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '15',
    cost: '5,00',
    total: '75,00' },
  { date: '27-Feb',
    item: 'Imasi',
    quantity: '15',
    cost: '17,00',
    total: '255,00' },
  { date: '27-Feb',
    item: 'Iwisa Pap 5kg',
    quantity: '10',
    cost: '20,00',
    total: '200,00' },
  { date: '27-Feb',
    item: 'Milk 1l',
    quantity: '20',
    cost: '7,00',
    total: '140,00' },
  { date: '27-Feb',
    item: 'Top Class Soy Mince',
    quantity: '15',
    cost: '8,00',
    total: '120,00' },
  { date: '28-Feb',
    item: 'Shampoo 1 litre',
    quantity: '2',
    cost: '20,00',
    total: '40,00' },
  { date: '28-Feb',
    item: 'Soap Bar',
    quantity: '3',
    cost: '3,00',
    total: '9,00' },
  { date: '28-Feb',
    item: 'Chakalaka Can',
    quantity: '3',
    cost: '8,50',
    total: '25,50' },
  { date: '28-Feb',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '2',
    cost: '8,50',
    total: '17,00' },
  { date: '28-Feb',
    item: 'Top Class Soy Mince',
    quantity: '5',
    cost: '11,00',
    total: '55,00' },
  { date: '01-Mar',
    item: 'Shampoo 1 litre',
    quantity: '2',
    cost: '20,00',
    total: '40,00' },
  { date: '01-Mar',
    item: 'Soap Bar',
    quantity: '5',
    cost: '3,00',
    total: '15,00' },
  { date: '01-Mar',
    item: 'Chakalaka Can',
    quantity: '3',
    cost: '8,50',
    total: '25,50' },
  { date: '01-Mar',
    item: 'Gold Dish Vegetable Curry Can',
    quantity: '2',
    cost: '8,50',
    total: '17,00' },
  { date: '01-Mar',
    item: 'Top Class Soy Mince',
    quantity: '3',
    cost: '11,00',
    total: '33,00' } ]
);
  });
});

describe("sales",function(){
  it("should return the sales for all the weeks", function(){
    var result = sales.Sales();
    assert.deepEqual(result, ['Coke 500ml'], ["Coke 500ml"], ["Milk 1l"], ['Gold Dish Vegetable Curry Can']);
  });
});
